air_temp_HMP45C:  
    - ['2018-06-01 00:00:00', '2018-10-19 15:00:00'] # Faulty HMP45C replaced the 2018-12-19 10:00:00
air_relhum_HMP45C:  
    - ['2018-06-01 00:00:00', '2018-10-19 15:00:00'] # Faulty HMP45C replaced the 2018-12-19 10:00:00
air_temp_min_HMP45C:  
    - ['2018-06-01 00:00:00', '2018-10-19 15:00:00'] # Faulty HMP45C replaced the 2018-12-19 10:00:00
air_temp_max_HMP45C:  
    - ['2018-06-01 00:00:00', '2018-10-19 15:00:00'] # Faulty HMP45C replaced the 2018-12-19 10:00:00