wind_speed_05103: 
    - ['2018-01-01 00:00:00', '2022-08-16 13:00:00'] # Instrument not connected yet
wind_dir_05103: 
    - ['2018-01-01 00:00:00', '2022-08-16 13:00:00'] # Instrument not connected yet
air_press_61205V: 
    - ['2022-11-10 04:00:00', '2023-01-28 12:30:00'] # Instrument intermittent malfunction not explained
    - ['2023-02-16 18:30:00', '2023-03-05 12:00:00'] # Instrument intermittent malfunction not explained
    - ['2023-11-28 00:00:00', '2023-11-29 12:00:00'] # Instrument intermittent malfunction not explained
    - ['2023-12-20 04:00:00', '2024-03-28 14:00:00'] # Instrument intermittent malfunction not explained
    - ['2024-12-12 17:00:00', '2025-12-18 00:30:00'] # Instrument intermittent malfunction not explained
    - ['2024-12-18 18:00:00', '2025-01-08 13:00:00'] # Instrument intermittent malfunction not explained
    - ['2025-08-15 09:00:00', '2025-08-15 11:00:00'] # Instrument intermittent malfunction not explained
air_press_LI7700: 
    - ['2023-10-06 10:00:00', '2024-06-02 11:00:00'] # Failure of the power supply board that affected pressure reading
air_press_IRGASON: 
    - ['2024-06-01 07:30:00', '2025-07-02 09:30:00'] # Bad calibration of the pressure sensor