calibration_dates: 
    - "2018-06-01 00:00:00"
    - "2019-06-01 12:00:00"
    - "2020-06-22 18:00:00"
    - "2021-08-05 12:00:00"
    - "2021-10-20 09:00:00"
    - "2022-06-13 14:30:00"
    - "2023-06-01 11:00:00"
    - "2024-06-01 20:00:00"
    - "2025-05-29 20:00:00"
invalid_intervals:
    - start: "2021-08-05 12:00:00"
      end: "2021-10-20 09:00:00"