calibration_dates:
    - "2018-10-01 00:00:00"
    - "2019-06-08 14:00:00"
    - "2020-06-18 14:00:00"
    - "2021-08-04 16:00:00"
    - "2022-06-19 13:00:00"
    - "2022-10-22 14:00:00"
    - "2023-05-29 13:30:00"
    - "2024-05-28 20:00:00"
    - "2025-06-03 20:00:00"
invalid_intervals:
    - start: "2022-02-15 17:30:00"
      end: "2022-02-26 06:00:00"
    - start: "2022-03-01 12:00:00"
      end: "2022-03-03 06:00:00"
    - start: "2022-03-04 17:00:00"
      end: "2022-03-11 23:00:00"
    - start: "2022-03-26 00:00:00"
      end: "2022-06-19 13:00:00"