calibration_dates:
    - "2018-10-01 00:00:00"
    - "2019-06-08 14:00:00"
    - "2020-06-18 14:00:00"
    - "2021-08-04 16:00:00"
    - "2022-06-19 13:00:00"
    - "2022-10-22 11:30:00"
    - "2023-05-29 13:00:00"
    - "2024-05-28 20:00:00"
    - "2025-06-03 20:00:00"
invalid_intervals: