calibration_dates:
    - "2018-05-15 00:00:00"
    - "2019-05-15 00:00:00"
    - "2020-05-15 00:00:00"
    - "2021-05-15 00:00:00"
    - "2022-05-15 00:00:00"
    - "2023-05-15 16:00:00"
    - "2024-05-15 16:00:00"
    - "2025-05-15 16:00:00"
invalid_intervals: